# Configuration for Task 2 (Slow - 50Hz)
alg: ltgate  # Options: ltgate, hlop, dsd
dt: 1e-3  # 1ms time step
tau_fast: 5e-3  # 5ms time constant for fast pathway
tau_slow: 1e-1  # 100ms time constant for slow pathway

# Dataset parameters
task: slow
classes: [5, 6, 7, 8, 9]
frame_rate: 50
frames: 20

# Training parameters
batch_size: 32
epochs: 100
learning_rate: 0.005
local_update_interval: 5  # Apply local update every N timesteps
